### ISSUE TITLE
Minimal vector tile C++ decoder and encoder

### ISSUE THREAD

**Issue by springmeyer** [mapbox/vtzero#1]
@Joto has created a solid design for new, higher performance and more minimalistic vector tile decoder and encoder as part of https://github.com/mapbox/vector-tile/issues/20. This `vtzero` repo will be the home for this work.

This implementation will only depend on protozero and will make no assumptions about the property, feature, or geometry storage you will decode into or encode from. Rather it will provide handlers for minimal geometry and property decoding and encoding. The https://github.com/mapbox/vector-tile will be re-written to be a higher level wrapper around vtzero for handling vtzero <-> geometry.hpp, projections, and other APIs that will depend on C++ modules in the `mapbox::` namespace.

@joto - let's use this ticket for the initial coordination. The next steps I'm seeing are:

 - [x] @springmeyer creates initial skeleton of repo based on [hpp-skel](https://github.com/mapbox/hpp-skel) from the @mapbox/core-tech team.
 - [x] @joto reviews and pings @springmeyer if any of the skeleton needs modified in major ways
 - [x] @joto tags latest protozero at 1.5.3 (as I think latest vtzero depends on it)
 - [x] @springmeyer packages protozero 1.5.3 in mason
 - [x] @springmeyer updates this repo to pull in protozero 1.5.3 - https://github.com/mapbox/vtzero/commit/19dc27ec3c3bfb572170edb6dd0f7b409a36bdea
 - [x] @joto moves the vtzero code over from vector-tile to here.

After that there will still be much to do. Like writing tests, benchmarks, and docs (tracked in [milestone 1](https://github.com/mapbox/vtzero/milestone/1)). As well as back-porting fixes we make here that are appropriate for hpp-skel. But we can handle all those things in followup tickets.

**Comment by springmeyer** [comment]
This work is now done thanks to a huge lift by @joto and the @mapbox/core-tech. Closing this now - next steps are better tests and docs:

 - Docs: https://github.com/mapbox/vtzero/issues/12
 - Tests: https://github.com/mapbox/vtzero/issues/13

**Comment by mapsam** [comment]
![tada-quack](https://user-images.githubusercontent.com/1943001/31524875-4b72dc38-af71-11e7-931b-fa75ca864b66.gif)
