### ISSUE TITLE
Create mvt fixtures for geometry tests

### ISSUE THREAD

**Issue by joto** [mapbox/vtzero#19]
The tests in `test/t/test_geometry.cpp` test the geometries in isolation by crafting special broken geometries. These should be ported to tests in [mvt-fixtures](https://github.com/mapbox/mvt-fixtures).

**Comment by mapsam** [comment]
@joto here's a list of the broken geometries I'm seeing in test/t/test_geometry.cpp

* geometry_decoder with incomplete point 
* geometry_decoder with linestring with equal points (is this broken - unsure by the name of the fixture) 
* geometry_decoder with polygon with wrong ClosePath count 
* geometry_decoder decoding linestring with int32 overflow in x coordinate 
* geometry_decoder decoding linestring with int32 overflow in y coordinate 
* geometry_decoder with multipoint with a huge count 

Other broken geometries in the pipeline:

* This PR adds a huge move_to count: https://github.com/mapbox/mvt-fixtures/pull/79

**Comment by mapsam** [comment]
Woops, didn't mean to close. Moving over here: https://github.com/mapbox/mvt-fixtures/issues/84
