### ISSUE TITLE
Remove extra "add_points"

### ISSUE THREAD

**Issue by flippmoke** [mapbox/vtzero#22]
As I was reviewing the code in `builder.hpp` I noticed that `point_feature_builder` has several repeated ways to add multiple points from a container type structure:

* https://github.com/mapbox/vtzero/blob/master/include/vtzero/builder.hpp#L404-L411
* https://github.com/mapbox/vtzero/blob/master/include/vtzero/builder.hpp#L427-L438
* https://github.com/mapbox/vtzero/blob/master/include/vtzero/builder.hpp#L452-L461

The first example requires a call to `std::distance` however, which I feel people might utilize with out knowing the other methods exist. Should we limit the number of methods here to encourage people to use the best method?

**Comment by joto** [comment]
I wanted to make this as easy to use as possible. And I just wrote a bunch of documentation for these functions hopefully making the performance issues clear. The version with `std::distance` works well with something like `std::vector` or an array where the `std::distance` call is cheap, so there is a reason to actually have it.

**Comment by flippmoke** [comment]
@joto but in that case isn't it better to use the `add_points_from_container`?

**Comment by joto** [comment]
In case of a vector, yes. But it will not work with a simple C array. But I don't feel that strongly about any of those functions, I simply implemented what I though might be useful. Maybe we should remove the functions we don't have an immediate use for and re-add them later if we need them.

**Comment by joto** [comment]
I thought some more about this and have a new aspect to add here: Usually what an application is probably interested in, is not the point in the vector tile coordinate system but in the overall coordinate system. So do we actually have many cases where we have a container with the vector tile coordinates for, say, a LineString? If at all we'll have a container with the coordinates in web mercator or something and then convert this on-the-fly to the tile coordinates. That made me think that maybe the [`create_vtzero_point`](
https://github.com/mapbox/vtzero/blob/master/include/vtzero/geometry.hpp#L60-L70) helper function is really not what's needed here.

Instead we might have some kind of transformator class. I implemented something experimental [here](https://github.com/mapbox/vtzero/pull/28) that shows what I am thinking.

**Comment by joto** [comment]
I have temporarily removed two versions of the `add_points()` function that are not used as far as I know. Please complain here if you are using these functions. If nobody will complain we'll remove those functions before a release.

**Comment by flippmoke** [comment]
>I thought some more about this and have a new aspect to add here: Usually what an application is probably interested in, is not the point in the vector tile coordinate system but in the overall coordinate system. So do we actually have many cases where we have a container with the vector tile coordinates for, say, a LineString? If at all we'll have a container with the coordinates in web mercator or something and then convert this on-the-fly to the tile coordinates. That made me think that maybe the create_vtzero_point helper function is really not what's needed here.

In general I have found this streaming approach is not possible. The reason is that we have to ensure or correct geometry as being valid or simple in the integer coordinates of the tiles. Simply converting from web merc to tile coordinates can cause invalid polygons for certain. Because of this it is often required to have the entire structure rather instead of a streaming approach.

I still think overall we should limit the total number of APIs unless we can think of great use cases for these. So for now I think removing these is the right idea.

**Comment by joto** [comment]
We have a release in production for a while now and the API works well, nothing to be done here.
