### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by joto** [mapbox/vtzero#24]
Vtzero uses exceptions in many cases to report invalid vector tile data. Those exceptions contain more or less detailed descriptions of what went wrong. What they don't tell you is **where** something went wrong. You'll get an exception and don't know which feature in which layer this is from. The user code can, of course, figure this out, because it was probably iterating over the layers and features and so it can tell you. But that means extra effort in the user code and you'll have to catch the exceptions and add this information somehow and then rethrow it or display it.

We could add code in vtzero to track the layer and feature index in the vector tile and add it to the exceptions. But this, of course, has some overhead. Is this something we want? Maybe in most cases where an error occurs we just want to ignore everything anyway and don't need detailed reports? Or maybe this is something so useful, we want to have it built in?

Opinions?

@springmeyer @flippmoke

**Comment by flippmoke** [comment]
Assuming that there is an error with someone's vector tile, it would be very difficult to fix for that individual and the steps would be to recreate the tile. Therefore, I do not think that we have to support an option such as this. The only advantage would be for our own debugging. I am okay with this depending on the time savings we are losing by adding debugging.

**Comment by springmeyer** [comment]
> Therefore, I do not think that we have to support an option such as this. The only advantage would be for our own debugging. I am okay with this depending on the time savings we are losing by adding debugging.

I agree 👍 . So, instead of adding this info to the exceptions, how about `vtzero` just provides a command line tool that does the catch/rethrow with that info? Then we'd be able to debug bad tiles with that tool and avoid the potential perf overhead and code complexity of it being in the code decoder.

**Comment by joto** [comment]
Okay, no tracking of layer/feature num inside vtzero. I have added display of the layer/feature num to `vtzero-show` example program. This can be used to debug bad tiles for the time being.
