### ISSUE TITLE
Do we care about sanitizing unsigned integer overflow on travis?

### ISSUE THREAD

**Issue by springmeyer** [mapbox/vtzero#27]
The clang docs note:

> -fsanitize=unsigned-integer-overflow: Unsigned integer overflows. Note that unlike signed integer overflow, unsigned integer is not undefined behavior. However, while it has well-defined semantics, it is often unintentional, so UBSan offers to catch it.

By reading the docs closely (confirmed by looking at https://github.com/llvm-mirror/clang/blob/master/include/clang/Basic/Sanitizers.def) it looks like `unsigned-integer-overflow` is enabled with the `-fsanitize=integer` group (and with `-fsanitize=unsigned-integer-overflow` specifically) but not by the `-fsanitize=undefined` group.

@joto I noticed https://github.com/mapbox/vtzero/commit/8320b87ed11cd48f4ef517e805e1968987bb2a45, which I think means we will no longer be testing `-fsanitize=unsigned-integer-overflow`. Should we add that back or are we fine not worrying about unsigned integer overflow (since it is defined)?

**Comment by joto** [comment]
Sorry, I misread the clang documentation. I understood that `undefined` is a strict superset of `integer` which is apperently wrong. I'll add the integer back in.
