### ISSUE TITLE
Asserts in set_point

### ISSUE THREAD

**Issue by joto** [mapbox/vtzero#31]
There are three asserts in the `set_point()` functions of the `linestring_feature_builder` and `polygon_feature_builder`:

1. https://github.com/mapbox/vtzero/blob/master/include/vtzero/builder.hpp#L812
2. https://github.com/mapbox/vtzero/blob/master/include/vtzero/builder.hpp#L1014
3. https://github.com/mapbox/vtzero/blob/master/include/vtzero/builder.hpp#L1018

(1) and (3) are used to enforce the spec rule (*"For any pair of (dX, dY) the dX and dY MUST NOT both be 0"*) (2) is used to make sure the last point is the same as the first point so the ClosePath works correctly.

I am not sure what the right behaviour in these cases is. If we leave them as asserts, the calling code has to make sure these conditions hold. If we throw an exception instead, this makes it easier for the calling code. On the other hand, it is an extra check that some code might not need (code that is already sure the geometries are okay) that costs time and resources (the `m_first_point` member would not be needed without check (2)).

Opinions? @springmeyer @flippmoke

**Comment by flippmoke** [comment]
I believe we have the following options here:
   * Silently not add points when they fail this case
   * Throw an exception when they fail this case
   * Return a `bool` to signify if the point was added or not
   * Leave the assert

I believe that returning a boolean might be the most friendly interface to deal with in this situation. However, if we do that there are all sorts of other checks and modifications we need to do if we are to use it in this case. This is the same if we silently do not add points. 

An assert makes sense, but I feel like it is really harsh in case of error, but I would like to reduce the number of possible exceptions that this can cause. 

We could shift some of this logic *up* into `vector-tile` and its builder scripts as a pre-checking event, but I want to see `vtzero` handle as much of the specification rules as possible. Overall, I would like to see `vtzero` handle this check but it might mean some re-thinking of the interface.

**Comment by joto** [comment]
Silently not adding the point is not an option, because the count would be wrong then and we have already set the count. Even if we didn't, ignoring a point might make a linestring invalid, for instance if it only had two points to begin with.

I prefer throwing an exception to returning a bool. Otherwise the return value can be ignored which isn't good in this case, because it would leave an invalid feature in the tile.

The assert really means: The calling code should have checked this already, we trust it. In release build it will not be there and if the caller didn't handle this correctly we will create invalid tiles.

However we are doing this, the calling code has to handle this case somehow. If there is only an assert, it has to do the checking itself, if there is an exception, it has to `rollback()` the feature correctly if it wants to go on writing the tile.

**Comment by springmeyer** [comment]
I have no strong opinions at this time, ping me again if you need me to look closer.

**Comment by joto** [comment]
I have thought about this some more and here are some new aspects: If we throw an exception in these functions, the exception has to be caught and handled, probably by calling `rollback()` on the `feature_builder`. That is inconvenient.

So maybe we have to turn the logic in the feature builder around: You have to call `commit()`, otherwise the destructor will do a `rollback()`. This way an exception in any of the code in the feature builder will automatically rollback the feature buing built leaving the layer builder in a valid state. You still have to catch this exception in your code but can immediately go to the next feature then or something like this. The price for this is an explicit `commit()` call that is then always needed. Alternatively we could remember in the `feature_builder` object that a call to `set_point` failed and do the `rollback()` instead of the `commit()` when the object is destructed, but this gets close to being magical.

To decide how to move forward here we really have to know which use case is the common one:
1. The user of the vtzero library makes sure itself that it is not feeding incorrect data (duplicate points or ring not closed) to vtzero.
2. The user of the vtzero library wants vtzero to check for this.

The current implementation with the `assert` is fine for (1). The implementation for (2) would have to use an exception or boolean return code from `set_point`.

We could also have two interfaces and leave the choice to the user. But this will get messy fast, because there are multiple overloads of the `set_point` function already and doubling them by adding a, say, `set_point_with_check()` function with several overloads doesn't seem appealing. Another option would be adding a template parameter to the `feature_builder` class that somehow specifies the behaviour, but, again, there isn't only one `feature_builder` class, but a whole hierarchy, making this somewhat unwieldy.

In terms of cost, doing the check always is probably not a huge thing. A bit more costly is keeping the `m_first_point` member in the `polygon_feature_builder` which is only needed for this check. The most expensive part, though, is the exception if it gets thrown, which should not happen too often.

**Comment by joto** [comment]
After chat with @flippmoke we have agreed on the way forward:
1. `set_point()` and similar functions now throw a `vtzero::geometry_exception` if there are two consecutive equal points or if the last point in a ring is not the same as the first point.
2. feature builder classes now rollback the current feature on destruction unless `commit()` has been called explicitly. This makes sure that exceptions due to (1) leave the layer in a valid state, ready to accept more features.

**This is a breaking change**, everbody using the builder interface must update their code! 

/cc @mapbox/core-tech @ericfischer
