### ISSUE TITLE
Mascot?

### ISSUE THREAD

**Issue by springmeyer** [mapbox/vtzero#33]
What about a friendly mascot for vtzero? Seeing the delightful `mvt-fixtures crew` at https://github.com/mapbox/mvt-fixtures makes me wonder if a great vtzero mascot could be one of those little creatures with a proud `0` in the middle (hole with cross) and some arms that are strongly holding up a globe? Or otherwise in a position as if it is holding something up (to get at the fact that vtzero is foundational)?

Thoughts?

/cc @mapsam @mapbox/core-tech @joto

**Comment by joto** [comment]
No action for a while. Closing. If anybody wants to work on a mascot, please do.
