### ISSUE TITLE
Document ownership relation between layer and feature

### ISSUE THREAD

**Issue by anandthakker** [mapbox/vtzero#36]
It looks to me like `vtzero::feature` depends on having a pointer to its `vtzero::layer` object (specifically for getting property data): 
 https://github.com/mapbox/vtzero/blob/62d26408f0b5fe21c0c78a32d9b0d77bac1196ab/include/vtzero/layer.hpp#L388-L396

However, this requirement isn’t enforced--it's possible, for instance, to do:

```cpp
vtzero::feature getFeature(vtzero::tile tile, std::string layer, uint64_t id) {
  return tile.get_layer_by_name(layer).get_feature_by_id(id);
}
```

and end up with a `feature` whose owning `layer` has been destroyed.

Since presumably the overhead of enforcing this with a `shared_ptr` would be undesirable, would it make sense to at least make a note of this in the documentation for `feature`?

**Comment by anandthakker** [comment]
> in the documentation for feature

Or, alternatively, in the intro to https://github.com/mapbox/vtzero/blob/master/doc/reading.md, where a similar requirement regarding the underlying data is already discussed.

**Comment by springmeyer** [comment]
Thanks for ticketing, this has come up before and is definitely worthwhile to document better. I'll defer to @joto for where to put it, but 👍  on getting this more obvious.
