### ISSUE TITLE
add_property is  slow

### ISSUE THREAD

**Issue by ccxxbb** [mapbox/vtzero#45]
when add 100 property value, add_property  is slow ,how to  optimize add_property

**Comment by joto** [comment]
You could give us some more information about what you are doing. From that one sentence it is difficult to figure out what you are doing and where there might be ways to improve it. I trust you have read the section [The advanced approach to adding properties](https://github.com/mapbox/vtzero/blob/master/doc/writing.md#the-advanced-approach-to-adding-properties) in the manual.

**Comment by springmeyer** [comment]
Agree with @joto that more information is needed (ideally a code sample that demonstrates the problem). Going to close, since there has not been a response from @ccxxbb.
