### ISSUE TITLE
Question: What coordinate system should I be writing coordinates in?

### ISSUE THREAD

**Issue by jumpinjackie** [mapbox/vtzero#47]
Hi there,

I'm experimenting with vtzero for creating MVT files and I can't quite grasp from the examples or documentation as to what coordinate system I am meant to be writing geometry coordinates in.

Let's assume I am trying to encode a polygon geometry whose coordinates are in EPSG:4326 (latitude/longitude). Do I:

 1. Write these coordinate as-is?
 2. Transform/clip the geometry to a 4096x4096 "pixel" screen space of the applicable tile such that the coordinates written are in the range between (0, 0) and (4095, 4095)? I gathered 4096 is the [default tile size](https://github.com/mapbox/vtzero/blob/29157250538f3a6ddf4abd73f35d0020a543f827/include/vtzero/layer.hpp#L60)
 3. Something else?

**Comment by loshhilov** [comment]
The GDAL MVT driver uses EPSG:3857 by default. No other thoughts have yet arisen :-)

**Comment by joto** [comment]
Usually with vector tiles you use Web Mercator (EPSG:3857) projection, but this is not required. You have to convert those coordinates into tile coordinates yourself, vtzero is a very low-level library and doesn't do this for you. Basically you have to split up the coordinate space by the number of tiles in a given zoom level and then convert what's left to the 4096 range (or use a different range, but usually the default is good).
