### ISSUE TITLE
feature_builder.add_tags(uint32_t key_idx, uint32_t value_idx)

### ISSUE THREAD

**Issue by springmeyer** [mapbox/vtzero#5]
It appears not possible currently to add tag elements directly to the `feature_builder_base` class as `uint32_t`.

Would it be possible to add them directly to bypass the expense of looking up the `uint32_t` idx via the layer's `std::map` in the case where the correct index is already known?

/cc @joto

**Comment by springmeyer** [comment]
> in the case where I already know the correct index.

And to facilitate this, I think would be ideal to be able to get the `uint32_it_range` object off the `feature` class with an accessor like:

```c++
uint32_it_range tag_range() const noexcept {
    return m_tags;
}
```

**Comment by joto** [comment]
This now works using the `get_index_pair()` function on the property iterator.

**Comment by springmeyer** [comment]
Thanks for adding getters 🙏  Are there also setters?

**Comment by joto** [comment]
Yes, there are. I'll write up some docs as soon as possible.
