### ISSUE TITLE
Is it possible to add empty layers in the tile_builder

### ISSUE THREAD

**Issue by bretttully** [mapbox/vtzero#58]
An [example mvt here](https://github.com/mapbox/mapnik-vector-tile/blob/master/examples/data/14_8716_8015.vector.mvt) contains layers with no geometries. I am using this as a test tile for creating a writer using vtzero, but I cannot figure out how to add an empty layer.

The use case is because, I think there is a difference between:
* my dataset (a collection of mvts) contains a particular layer but an individual mvt may not have any features for that layer
* my dataset does not contain a layer by that name

Currently, as far as I can understand, vtzero cannot distinguish between the two. Is that correct? Does the spec permit empty layers? 

In [writing.md](https://github.com/mapbox/vtzero/blob/master/doc/writing.md) there is a statement:

> The tile builder is smart enough to not add empty layers, so you can start out with all the layers you might need and if some of them stay empty, they will not be added to the tile when serialize() is called.

Which I assume means that the inability to ignore empty layers is intentional.

**Comment by joto** [comment]
It is not possible to add a layer without features to a vector tile with vtzero. The standard says "*A layer SHOULD contain at least one feature.*". That's not a "*MUST*", so layers without features are technically allowed but discouraged.

But I can't think of a reason why you wanted to add an empty layer. Vector tiles are supposed to be as small as possible, so adding extra data that doesn't do anything seems wasteful. And the layer metadata is not enough to somehow interpret what this layer is representing, so you always need an external configuration anyway with a list of layers and how they are supposed to be rendered or whatever.

**Comment by bretttully** [comment]
Cool, makes sense. Rely on dataset metadata to distinguish the two cases I mentioned, rather than the mvts themselves.

Thanks for the response.
