### ISSUE TITLE
"Tag" vs. "Property"

### ISSUE THREAD

**Issue by joto** [mapbox/vtzero#6]
The vector tile spec uses "tag" and "property" somewhat interchangably. Which is the preferred term?

/cc @flippmoke, @springmeyer, @mapsam

**Comment by flippmoke** [comment]
I think we should tend to use property, but tag is describing the field `tags`, which is why it is still around.

**Comment by mapsam** [comment]
I believe [Google refers](https://developers.google.com/protocol-buffers/docs/overview) to these as "fields", which may or may not be a helpful addition to this conversation 😛

**Comment by joto** [comment]
@mapsam "fields" are the things in the protobuf spec, "tags" or "properties" are in the mvt spec. Different levels.

**Comment by mapsam** [comment]
Ah, I see. 👍 "property"
